from sqlalchemy import Column, Integer, String, DateTime, Text, Boolean, ForeignKey, Enum as SQLEnum, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from enum import Enum
import uuid
from sqlalchemy.dialects.postgresql import UUID

from app.core.database import Base


class MatchStatus(Enum):
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    DISPUTED = "DISPUTED"


class Match(Base):
    __tablename__ = "matches"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    tournament_id = Column(UUID(as_uuid=True), ForeignKey("tournaments.id"), nullable=False)
    
    # Teams
    team1_id = Column(UUID(as_uuid=True), ForeignKey("teams.id"))
    team2_id = Column(UUID(as_uuid=True), ForeignKey("teams.id"))
    
    # Match details
    round_number = Column(Integer, nullable=False)
    match_number = Column(Integer, nullable=False)
    bracket_position = Column(String)  # e.g., "Winners Bracket R1M1"
    
    # Scheduling
    scheduled_time = Column(DateTime(timezone=True))
    actual_start_time = Column(DateTime(timezone=True))
    actual_end_time = Column(DateTime(timezone=True))
    
    # Results
    status = Column(SQLEnum(MatchStatus), default=MatchStatus.SCHEDULED)
    team1_score = Column(Integer, default=0)
    team2_score = Column(Integer, default=0)
    winner_id = Column(UUID(as_uuid=True), ForeignKey("teams.id"))
    
    # Match details
    best_of = Column(Integer, default=1)  # Best of X games
    game_details = Column(JSON)  # Store individual game results
    
    # AI-generated summary
    ai_summary = Column(Text)  # Generated by Gemini API
    summary_generated_at = Column(DateTime(timezone=True))
    
    # Match settings
    map_pool = Column(JSON)  # Available maps
    selected_maps = Column(JSON)  # Maps played
    server_info = Column(JSON)  # Server details for the match
    
    # Administrative
    reported_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id"))  # Who reported the result
    verified_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id"))  # Admin who verified
    is_verified = Column(Boolean, default=False)
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Additional notes
    notes = Column(Text)
    admin_notes = Column(Text)
    
    # Relationships
    tournament = relationship("Tournament", back_populates="matches")
    team1 = relationship("Team", foreign_keys=[team1_id], back_populates="home_matches")
    team2 = relationship("Team", foreign_keys=[team2_id], back_populates="away_matches")
    winner = relationship("Team", foreign_keys=[winner_id])
    reported_by = relationship("User", foreign_keys=[reported_by_id])
    verified_by = relationship("User", foreign_keys=[verified_by_id])
    game_results = relationship("GameResult", back_populates="match")


class GameResult(Base):
    __tablename__ = "game_results"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    match_id = Column(UUID(as_uuid=True), ForeignKey("matches.id"), nullable=False)
    
    game_number = Column(Integer, nullable=False)  # Game 1, 2, 3 etc. in a series
    map_played = Column(String)
    
    # Results
    team1_score = Column(Integer, default=0)
    team2_score = Column(Integer, default=0)
    winner_id = Column(UUID(as_uuid=True), ForeignKey("teams.id"))
    
    # Game duration and details
    duration_minutes = Column(Integer)
    game_details = Column(JSON)  # Game-specific stats
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    match = relationship("Match", back_populates="game_results")
    winner = relationship("Team", foreign_keys=[winner_id])


class Notification(Base):
    __tablename__ = "notifications"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    
    # Notification content
    title = Column(String, nullable=False)
    message = Column(Text, nullable=False)
    notification_type = Column(String)  # match_update, tournament_update, etc.
    
    # Related entities
    tournament_id = Column(UUID(as_uuid=True), ForeignKey("tournaments.id"))
    match_id = Column(UUID(as_uuid=True), ForeignKey("matches.id"))
    team_id = Column(UUID(as_uuid=True), ForeignKey("teams.id"))
    
    # Status
    is_read = Column(Boolean, default=False)
    is_email_sent = Column(Boolean, default=False)
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    user = relationship("User")
    tournament = relationship("Tournament")
    match = relationship("Match")
    team = relationship("Team")